name: Firebase Deployment Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (required for Firebase CLI)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use a Node.js version compatible with Firebase

    # Step 3: Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Step 4: Authenticate with Firebase
    - name: Authenticate with Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: echo "Authenticated with Firebase"

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
